use api instead of implementation; ios build fails
iOSApp.swift:8:14: error: cannot find 'MainViewControllerKt' in scope init() { MainViewControllerKt.initialize() }